set_property PACKAGE_PIN G22 [get_ports In_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports In_CLK]
set_property PACKAGE_PIN D26 [get_ports RST_N]
set_property IOSTANDARD LVCMOS33 [get_ports RST_N]
set_property PACKAGE_PIN A17 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN B17 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property PACKAGE_PIN H26 [get_ports Key_Signal]
set_property IOSTANDARD LVCMOS33 [get_ports Key_Signal]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_CLK_100M/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {Time_Counter_Big[0]} {Time_Counter_Big[1]} {Time_Counter_Big[2]} {Time_Counter_Big[3]} {Time_Counter_Big[4]} {Time_Counter_Big[5]} {Time_Counter_Big[6]} {Time_Counter_Big[7]} {Time_Counter_Big[8]} {Time_Counter_Big[9]} {Time_Counter_Big[10]} {Time_Counter_Big[11]} {Time_Counter_Big[12]} {Time_Counter_Big[13]} {Time_Counter_Big[14]} {Time_Counter_Big[15]} {Time_Counter_Big[16]} {Time_Counter_Big[17]} {Time_Counter_Big[18]} {Time_Counter_Big[19]} {Time_Counter_Big[20]} {Time_Counter_Big[21]} {Time_Counter_Big[22]} {Time_Counter_Big[23]} {Time_Counter_Big[24]} {Time_Counter_Big[25]} {Time_Counter_Big[26]} {Time_Counter_Big[27]} {Time_Counter_Big[28]} {Time_Counter_Big[29]} {Time_Counter_Big[30]} {Time_Counter_Big[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {Time_Counter[0]} {Time_Counter[1]} {Time_Counter[2]} {Time_Counter[3]} {Time_Counter[4]} {Time_Counter[5]} {Time_Counter[6]} {Time_Counter[7]} {Time_Counter[8]} {Time_Counter[9]} {Time_Counter[10]} {Time_Counter[11]} {Time_Counter[12]} {Time_Counter[13]} {Time_Counter[14]} {Time_Counter[15]} {Time_Counter[16]} {Time_Counter[17]} {Time_Counter[18]} {Time_Counter[19]} {Time_Counter[20]} {Time_Counter[21]} {Time_Counter[22]} {Time_Counter[23]} {Time_Counter[24]} {Time_Counter[25]} {Time_Counter[26]} {Time_Counter[27]} {Time_Counter[28]} {Time_Counter[29]} {Time_Counter[30]} {Time_Counter[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK]
